### ISSUE TITLE
404 page not found ，  正常吗？

### ISSUE THREAD

**Issue by danel8** [slippersheepig/ChatGPT-to-API#1]
试了好几遍，openai的api有欢迎信息的。
怎么确定是否中转成功啊

**Comment by slippersheepig** [comment]
不要用浏览器访问，那是get请求，是无效的，会返回404。随便找个支持设置代理地址的chatgpt项目，能正常返回对话就代表成功了

**Comment by slippersheepig** [comment]
> 试了好几遍，openai的api有欢迎信息的。 怎么确定是否中转成功啊

readme已增加用例，请自行测试
