### ISSUE TITLE
一直提示Failed to fetch

### ISSUE THREAD

**Issue by xiewei3536** [slippersheepig/ChatGPT-to-API#2]
大佬请问这是什么问题？已经按照教程部属完，但在Nextchat一直提示这错误

{
  "error": true,
  "message": "Failed to fetch"
}

**Comment by slippersheepig** [comment]
刚同步更新了原作者的commit，现在再试试，如果还是不行的话：  
1.检查你的endpoint地址是否设置正确  
2.直接使用IP访问chatgpt.com看是否能正常访问  
如果都没问题，那可能跟作者目前遇到的issue有关，详见作者[github](https://github.com/xqdoo00o/ChatGPT-to-API)
