### ISSUE TITLE
HAR登录是否失效？

### ISSUE THREAD

**Issue by sebastian0619** [slippersheepig/ChatGPT-to-API#4]
<img width="467" alt="image" src="https://github.com/slippersheepig/ChatGPT-to-API/assets/39752847/4083bd0f-803a-4997-82d7-b2ada4ec51f9">
如图所示，日志体现的内容应该是已经读取到了har文件。但是在生成access token的步骤出错了
另如下图，测试ping接口正常，但调用v1/chat/completions则返回500的错误

尝试过将access_tokens.json映射出来，但是运行时并没有写入access token
<img width="85" alt="image" src="https://github.com/slippersheepig/ChatGPT-to-API/assets/39752847/28cfbafc-12c7-46db-8eb7-a532d8d82b22">

初步排除是服务器本身的问题，在两个美国服务器、一个大阪服务器均部署尝试后出现该等错误。服务器本身搭设的其他逆向项目都可正常运行。

**Comment by slippersheepig** [comment]
疑似登录出CF盾了，不过不确定，请到作者[issue](https://github.com/xqdoo00o/ChatGPT-to-API/issues)反馈。

**Comment by sebastian0619** [comment]
> 已在作者issue找到作者提供的解决方案 “更新最新版，请添加下环境变量export CLIENT_PROFILE=[这里的键名](https://github.com/bogdanfinn/tls-client/blob/master/profiles/profiles.go#L10)以及export UA=浏览器的UA” [xqdoo00o/ChatGPT-to-API#68 (comment)](https://github.com/xqdoo00o/ChatGPT-to-API/issues/68#issuecomment-2172975342)

感谢大佬... 就是有点没看懂
是在环境变了添加
CLIENT_PROFILE=chrome_103
然后从F12复制当前浏览器的UserAgent到
UA=xxxx么？

感谢..

**Comment by slippersheepig** [comment]
> > 已在作者issue找到作者提供的解决方案 “更新最新版，请添加下环境变量export CLIENT_PROFILE=[这里的键名](https://github.com/bogdanfinn/tls-client/blob/master/profiles/profiles.go#L10)以及export UA=浏览器的UA” [xqdoo00o/ChatGPT-to-API#68 (comment)](https://github.com/xqdoo00o/ChatGPT-to-API/issues/68#issuecomment-2172975342)
> 
> 感谢大佬... 就是有点没看懂 是在环境变了添加 CLIENT_PROFILE=chrome_103 然后从F12复制当前浏览器的UserAgent到 UA=xxxx么？
> 
> 感谢..

对，我的readme里有样例，参考如下填写即可
CLIENT_PROFILE: Chrome_124
UA: Mozilla/5.0

不客气
